<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_hi</name>
   <tag></tag>
   <elementGuidId>82e838d3-631f-4f59-bc72-daed8de8ce45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container-summernote28525']/div[2]/div[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.note-editable</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>771e9af5-d8aa-4f61-9d6e-fab5440fd23b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>note-editable</value>
      <webElementGuid>06341d1b-c5b0-4ac4-8c01-64bd3a645bd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>contenteditable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c5f6372b-808a-4094-b9c9-479ff4e9ea87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>hi</value>
      <webElementGuid>9d58f925-82d5-40c7-9fc4-2d656bcf9823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container-summernote28525&quot;)/div[@class=&quot;note-editor&quot;]/div[@class=&quot;note-editable&quot;]</value>
      <webElementGuid>a6fb876f-b972-4c27-8eb6-621958680e5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container-summernote28525']/div[2]/div[6]</value>
      <webElementGuid>bc653161-85d1-4049-a023-502ad5b25314</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Verdana'])[1]/following::div[6]</value>
      <webElementGuid>eb33b951-98ea-4f93-bc81-bdc3da6d3a82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Times New Roman'])[1]/following::div[6]</value>
      <webElementGuid>6d5ec361-4a95-4164-97b0-d2a63f50bc59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quick Response'])[2]/preceding::div[6]</value>
      <webElementGuid>ec603d54-d44e-4d9c-a427-d6252c904b23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send'])[1]/preceding::div[8]</value>
      <webElementGuid>eee1acde-97e1-4d85-babe-3bb9d5274e81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='hi']/parent::*</value>
      <webElementGuid>d6b9f758-dd5c-4aeb-9a4b-dd19a99e28b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[6]</value>
      <webElementGuid>3bd93531-2c4b-4d9a-978c-bf9545a67fba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'hi' or . = 'hi')]</value>
      <webElementGuid>1010ee1f-1045-4d48-a818-c4eae3d6ab0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
