<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Low</name>
   <tag></tag>
   <elementGuidId>ce6f3829-acb0-4001-ae7a-96bd3df8956b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-FieldPriorityId28525-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-FieldPriorityId28525-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>74d56ccb-8706-4d83-8913-a96048e3fac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>b9c1fdb1-ef5f-453e-b320-77bb58c0b885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-FieldPriorityId28525-container</value>
      <webElementGuid>e7523bcb-ddfe-438c-afa8-54cff584245d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Low</value>
      <webElementGuid>09cad79d-01f6-4201-993e-cbb30e08f5ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Low</value>
      <webElementGuid>f98d7697-fd23-4e6d-8bb2-a3be155fc1e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-FieldPriorityId28525-container&quot;)</value>
      <webElementGuid>a0705396-9990-4f8e-be3e-6affd4313580</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-FieldPriorityId28525-container']</value>
      <webElementGuid>0846dd1b-e00b-4eec-884d-ecbe3db2789d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='scroll_status28525']/div[2]/div/span/span/span/span</value>
      <webElementGuid>6700c7a9-5d53-412c-9ee9-6afdfa2120e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Priority'])[6]/following::span[4]</value>
      <webElementGuid>95416c0b-945f-4103-849a-e3609c153b16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Closed'])[7]/following::span[6]</value>
      <webElementGuid>36d86be7-c24d-438c-be8d-a8c4fe0dbfe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Category'])[8]/preceding::span[3]</value>
      <webElementGuid>8e60670b-d506-46a6-8e1a-9581ac3639a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Options'])[4]/preceding::span[3]</value>
      <webElementGuid>d45d8f14-e442-48d9-9c5e-20ec309ea6f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/span/span/span</value>
      <webElementGuid>688b1d84-aa71-404d-9ce3-fc30855cf7fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-FieldPriorityId28525-container' and @title = 'Low' and (text() = 'Low' or . = 'Low')]</value>
      <webElementGuid>e93e6df4-cb2e-4033-9120-70db664e4e54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
