<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search</name>
   <tag></tag>
   <elementGuidId>bdc8d5ad-ad8a-4048-8ad4-f4b67b597c34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id='searchbtn'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#form_tab_report_agent_activity > div.animated.fadeInRight.p-t-xs > div.wrapper.wrapper-content.p-t-none > div.ibox-content > div.row.no-margins > div.col-sm-2.pull-right.p-r-none.m-b > div.row.no-margins > div.btn-group.pull-right > #searchbtn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dce0d35c-85b4-451a-91f1-6476dd5d521c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>58fa575a-8c7a-47f3-9bf0-97c4a574464f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchbtn</value>
      <webElementGuid>9cf88f81-c152-4c3d-a472-03e8a1a16719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-sm animated fadeInRight</value>
      <webElementGuid>8eab0a29-7e38-4ea8-ba00-eefc607355df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>335bb692-1434-4291-b673-af12e15a117d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
									 Search
								</value>
      <webElementGuid>50a9d061-cfa1-4a09-8fc6-63c493d88904</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_tab_report_agent_activity&quot;)/div[@class=&quot;animated fadeInRight p-t-xs&quot;]/div[@class=&quot;wrapper wrapper-content p-t-none&quot;]/div[@class=&quot;ibox-content&quot;]/div[@class=&quot;row no-margins&quot;]/div[@class=&quot;col-sm-2 pull-right p-r-none m-b&quot;]/div[@class=&quot;row no-margins&quot;]/div[@class=&quot;btn-group pull-right&quot;]/button[@id=&quot;searchbtn&quot;]</value>
      <webElementGuid>6f376db9-b823-49c2-97ad-5a434d1720b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@id='searchbtn'])[2]</value>
      <webElementGuid>ce0e989d-7836-4446-9c41-9e781d99f0fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_tab_report_agent_activity']/div/div/div/div/div/div/div/button</value>
      <webElementGuid>05bc9581-e39a-4b56-a288-51b99c1f395e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Report Agent Activity'])[1]/following::button[1]</value>
      <webElementGuid>2aa87501-58bb-4f94-b6a9-89c74f3fa105</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Whatsapp'])[11]/following::button[1]</value>
      <webElementGuid>57369b6d-1281-4609-8c93-c47146a2e5bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Team'])[20]/preceding::button[2]</value>
      <webElementGuid>7f0d8c46-a13a-4929-8feb-a41a3d7308a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Agent'])[6]/preceding::button[2]</value>
      <webElementGuid>ad05345b-89b4-4356-8e6d-a49f6bed681d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/form/div/div/div/div/div/div/div/button</value>
      <webElementGuid>f37dcf08-f55f-4cdf-b6b1-a34853d1fb54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'search' and @id = 'searchbtn' and @type = 'button' and (text() = '
									 Search
								' or . = '
									 Search
								')]</value>
      <webElementGuid>745e4bce-febb-4aef-9c34-0b82cbd65882</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
