<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Month</name>
   <tag></tag>
   <elementGuidId>f1955af6-02bb-4170-90c4-24403e3a5557</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='select2-searchperiodetab_report_agent_activity-result-kes3-month']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-searchperiodetab_report_agent_activity-result-kes3-month</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>497e0b6b-be63-4b5d-a1d4-2d119a44a430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--highlighted</value>
      <webElementGuid>625932c6-8aa1-44e4-a12a-5d947e7a93f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-searchperiodetab_report_agent_activity-result-kes3-month</value>
      <webElementGuid>351d623e-198b-4e71-b501-996205c63910</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>treeitem</value>
      <webElementGuid>266da1bb-7290-4433-abca-750f9db7a956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a3b0cb79-df53-4cac-b577-dfef099cd21a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Month</value>
      <webElementGuid>887eafea-6334-42b9-a10c-357bd47b57fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-searchperiodetab_report_agent_activity-result-kes3-month&quot;)</value>
      <webElementGuid>750b9996-3198-4b2a-823a-20ae43ff346d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='select2-searchperiodetab_report_agent_activity-result-kes3-month']</value>
      <webElementGuid>3a1cdbc7-d11b-4411-b38a-174afe5c73b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select2-searchperiodetab_report_agent_activity-results']/li[3]</value>
      <webElementGuid>e3ca9a6f-848c-496c-b21b-f94157c3a8cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Week'])[6]/following::li[1]</value>
      <webElementGuid>2b96a302-0ed2-4eeb-9a71-9da89cff59f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Today'])[17]/following::li[2]</value>
      <webElementGuid>d2c195ae-b473-45d1-b3b0-aeccb926b252</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Periode'])[6]/preceding::li[1]</value>
      <webElementGuid>76e62bf9-af28-4c20-807e-e606f25c9642</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/ul/li[3]</value>
      <webElementGuid>f8fb56d4-1dd6-4cdd-b954-43d8e17ee9f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-searchperiodetab_report_agent_activity-result-kes3-month' and (text() = 'Month' or . = 'Month')]</value>
      <webElementGuid>afe0b3b6-c4b2-4f43-9024-02c5621f1725</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
