<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Today</name>
   <tag></tag>
   <elementGuidId>0452f678-c690-4270-a2e4-ce8f5af2be23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-searchperiodetab_report_agent_activity-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-searchperiodetab_report_agent_activity-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4f3bfdfb-77b7-4ace-9555-db4bc1592b01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>9cc4f239-5cdc-4cf4-8d3e-9b0495266e61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-searchperiodetab_report_agent_activity-container</value>
      <webElementGuid>823b2373-9195-4e2c-956f-136a1964eb26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Today</value>
      <webElementGuid>c702d17c-3be9-4a14-b419-2eb58334c729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Today</value>
      <webElementGuid>80bd3ec5-cb2e-4e88-be81-e1fecb8bd39b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-searchperiodetab_report_agent_activity-container&quot;)</value>
      <webElementGuid>3364ea66-fb80-47bb-929d-cd7a1a9314c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-searchperiodetab_report_agent_activity-container']</value>
      <webElementGuid>57d00a21-546c-4fe6-92fe-c8d745c74cd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='advfiltertab_report_agent_activity']/div/div[3]/span/span/span/span</value>
      <webElementGuid>41c863fe-7933-4da0-891f-901926fed778</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Agent'])[6]/following::span[6]</value>
      <webElementGuid>ee75fa2c-0032-4b64-8dc0-9c28a84fa2c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Team'])[20]/following::span[12]</value>
      <webElementGuid>3d544bf0-c5c8-4acb-a1dd-d4955ca20bd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Processing...'])[5]/preceding::span[5]</value>
      <webElementGuid>00f446b7-5654-4643-9482-ba473912810f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copy'])[5]/preceding::span[5]</value>
      <webElementGuid>717d94b2-be88-4a2d-a58f-c0e930fe7f09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/form/div/div/div/div/div[2]/div/div[3]/span/span/span/span</value>
      <webElementGuid>9a52c705-160c-49ab-8709-92850cb7e72b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-searchperiodetab_report_agent_activity-container' and @title = 'Today' and (text() = 'Today' or . = 'Today')]</value>
      <webElementGuid>a5f20378-0226-4da5-b594-7570ff8cfda0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
