<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Month</name>
   <tag></tag>
   <elementGuidId>fbf65377-9a23-47da-9e0b-6984d16bd6f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-searchperiodetab_report_agent_activity-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-searchperiodetab_report_agent_activity-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9234c545-5294-413f-995c-30255dacddb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>a57221df-ad20-4e38-998e-d4a23e181b00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-searchperiodetab_report_agent_activity-container</value>
      <webElementGuid>6ba06386-6e28-41bb-b7da-56417539b4fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Month</value>
      <webElementGuid>c869c6b6-4539-4e05-a5c4-cfd141d91a72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Month</value>
      <webElementGuid>5927f77c-7146-4c6d-b9df-aca64918b9cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-searchperiodetab_report_agent_activity-container&quot;)</value>
      <webElementGuid>85b23a54-34ea-44d1-960b-6543763b7596</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-searchperiodetab_report_agent_activity-container']</value>
      <webElementGuid>94ca4b32-f23a-4d81-9d2c-ceeb9f612c8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='advfiltertab_report_agent_activity']/div/div[3]/span/span/span/span</value>
      <webElementGuid>cf00d0db-b82b-454d-aad6-1fd2f026e669</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Agent'])[6]/following::span[6]</value>
      <webElementGuid>618acd70-20a6-4914-b8dd-000a8d84cd18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Team'])[20]/following::span[12]</value>
      <webElementGuid>1c75d408-1c81-4d75-aa21-2402ea0becbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Processing...'])[5]/preceding::span[5]</value>
      <webElementGuid>7556d04f-5ea4-4440-a195-5efb9d9eb600</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copy'])[5]/preceding::span[5]</value>
      <webElementGuid>a51fdc5f-12c4-4808-99e5-58d46dafd256</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/form/div/div/div/div/div[2]/div/div[3]/span/span/span/span</value>
      <webElementGuid>a19ba0bd-b56d-47ba-acdc-de792fd1944d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-searchperiodetab_report_agent_activity-container' and @title = 'Month' and (text() = 'Month' or . = 'Month')]</value>
      <webElementGuid>74d6947a-0d47-4176-8187-31076c8ab94f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
