<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select Agent</name>
   <tag></tag>
   <elementGuidId>062138c7-f16d-4d63-9abf-d1aabffde976</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-fieldSelectPicIdtab_report_agent_activity-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-fieldSelectPicIdtab_report_agent_activity-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>74c255ae-e97a-43b9-9526-6d972d066a85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>e156c7ff-9e76-4f3b-ad7e-577f95d44cab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-fieldSelectPicIdtab_report_agent_activity-container</value>
      <webElementGuid>19af9055-8b9f-426f-8f76-73c4cc7a4dba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Select Agent</value>
      <webElementGuid>d2a21e7b-26d3-4357-880c-63e4bdd389e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Agent</value>
      <webElementGuid>c8f91480-9aad-425a-9ac8-88e9b7aa35e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-fieldSelectPicIdtab_report_agent_activity-container&quot;)</value>
      <webElementGuid>39f20495-e3a3-4b1d-9173-03047f9edfc0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-fieldSelectPicIdtab_report_agent_activity-container']</value>
      <webElementGuid>b042ce7c-8fcd-4337-bcff-5d3427b4217f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='advfiltertab_report_agent_activity']/div/div[2]/span/span/span/span</value>
      <webElementGuid>83af329b-3e84-4998-acaa-dbe7883b51ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Team'])[20]/following::span[6]</value>
      <webElementGuid>90f45c97-8a80-44c8-9181-aff428765d9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Today'])[11]/preceding::span[3]</value>
      <webElementGuid>1e4783e2-489d-456c-9c89-30392b38acf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Processing...'])[5]/preceding::span[11]</value>
      <webElementGuid>6085d976-f614-476f-a571-dca040a52785</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/div[2]/div/div[2]/span/span/span/span</value>
      <webElementGuid>86638c13-fd1c-4dc3-8090-cd3c04f66089</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-fieldSelectPicIdtab_report_agent_activity-container' and @title = 'Select Agent' and (text() = 'Select Agent' or . = 'Select Agent')]</value>
      <webElementGuid>7a6cb226-d116-4b3d-98bd-ef5dbc47f406</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
