<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search_advbtncategory_table_010</name>
   <tag></tag>
   <elementGuidId>cfa1691f-896b-4e95-8bab-2f8d5b8876c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='advbtncategory_table_010']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#advbtncategory_table_010</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9b0d84c8-7e21-4091-bf3e-12775f2e0978</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>advbtncategory_table_010</value>
      <webElementGuid>f0bd30d4-d9d1-418e-8bfb-35eeef0d8fb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-sm active</value>
      <webElementGuid>f86722e7-7681-43d9-9fc7-f0358483f682</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d1f14c24-b0bd-41ae-92ec-87e50df623bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;advbtncategory_table_010&quot;)</value>
      <webElementGuid>f12a132a-95c3-4001-8d0a-8cfa272c9a17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='advbtncategory_table_010']</value>
      <webElementGuid>31e8028f-ca57-449d-9d77-9c73676cbf9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='scroll_content_categorycategory_table_010']/div/div/div/div/div/div/button[2]</value>
      <webElementGuid>91943bb2-0549-4c0f-88f3-508eb3f36f1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Report Category'])[1]/following::button[2]</value>
      <webElementGuid>6413f6f9-859c-4209-ac8c-623b1f3e1f8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Category'])[16]/preceding::button[1]</value>
      <webElementGuid>d3a8f1d4-1172-478e-b825-d9ab2142c98a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Contact Type'])[2]/preceding::button[1]</value>
      <webElementGuid>75f4ea18-711a-45ce-b8b2-9656079b1c3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/div/div/div/div/div/div/div/button[2]</value>
      <webElementGuid>ff5d7bbc-841c-4889-bbe9-17459effa0fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'advbtncategory_table_010' and @type = 'button']</value>
      <webElementGuid>db0d19e0-dc3d-4be6-9fb8-ebdc24fac0b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
