<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search</name>
   <tag></tag>
   <elementGuidId>1f1d6a4a-d378-4e7d-92dc-b2b99f45aef4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='searchbtncategory_table_010']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#searchbtncategory_table_010</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>62ef10fc-ed6a-4c01-a3f2-8403b97fd740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchbtncategory_table_010</value>
      <webElementGuid>27bc682c-3363-4beb-bcc8-dedb0046bd09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-sm animated fade-in-right</value>
      <webElementGuid>cdaebafb-e3bb-4ca3-b8bb-e23192d1f40f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9f6323a2-77cc-49c2-9c99-42dde01e2478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
           Search
        </value>
      <webElementGuid>cc7b7760-f989-4e1f-aa76-6189d64696b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchbtncategory_table_010&quot;)</value>
      <webElementGuid>93921586-4f09-4793-8602-67a1bb1403be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='searchbtncategory_table_010']</value>
      <webElementGuid>4945d6ba-1cf3-4ac9-a87d-eee70509b2e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='scroll_content_categorycategory_table_010']/div/div/div/div/div/div/button</value>
      <webElementGuid>8796e4fb-9fec-4f46-9be4-f23bf82b11b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Report Category'])[1]/following::button[1]</value>
      <webElementGuid>d2b18cc2-2393-445b-bbbc-a3eb3b82f84a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Category Media'])[1]/following::button[1]</value>
      <webElementGuid>a5feda85-e48d-4a70-aa85-69ae94425253</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Category'])[16]/preceding::button[2]</value>
      <webElementGuid>44ce3d7b-80d7-4c8d-9147-6e62749df2d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Contact Type'])[2]/preceding::button[2]</value>
      <webElementGuid>23e4b2c0-4a7e-4e13-ab30-c38911cd4538</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/div/div/div/div/div/div/div/button</value>
      <webElementGuid>d0cf4505-e6a7-41e9-970d-c86644c071fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'searchbtncategory_table_010' and @type = 'button' and (text() = '
           Search
        ' or . = '
           Search
        ')]</value>
      <webElementGuid>b8d9c6b2-e681-4440-91f9-903494e991d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
