<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Today</name>
   <tag></tag>
   <elementGuidId>cf79116d-b9e6-416a-9439-c99da8d98914</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-searchperiodecategory_table_010-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-searchperiodecategory_table_010-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e00cb84c-c559-4ef9-87a7-5161ed4c177e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>77cc7015-f504-4c7c-9598-c643eef06535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-searchperiodecategory_table_010-container</value>
      <webElementGuid>2d015eb5-e7c0-4caa-9ac6-b1f88595fbd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Today</value>
      <webElementGuid>a8cbde00-a9ec-4ceb-a11d-6fec80661a78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Today</value>
      <webElementGuid>2a70bf85-fab6-44a5-96f3-93c719459d75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-searchperiodecategory_table_010-container&quot;)</value>
      <webElementGuid>af2a459b-4b1a-4843-85c2-b5aa2aa52551</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-searchperiodecategory_table_010-container']</value>
      <webElementGuid>c294605c-735f-4ff2-ade5-f20a07e1a9b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='advfiltercategory_table_010']/div/div[3]/span/span/span/span</value>
      <webElementGuid>7601aec5-67ee-4d6d-97b3-11c88562bde6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Product'])[12]/following::span[6]</value>
      <webElementGuid>7cce9769-f7e7-45df-8c1d-963732a05257</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Region'])[18]/following::span[12]</value>
      <webElementGuid>a8f028a8-7e26-4637-8e3d-686c0ef11248</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Omni Team'])[11]/preceding::span[5]</value>
      <webElementGuid>16d267a2-6727-41fa-af0f-c734efe32f81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Region'])[20]/preceding::span[11]</value>
      <webElementGuid>2b26727a-d7dd-4c89-a59e-e8fa5143dd21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/div/div/div/div/div[2]/div/div[3]/span/span/span/span</value>
      <webElementGuid>cbffa369-e9c9-4817-85cb-51dbc2ef1324</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-searchperiodecategory_table_010-container' and @title = 'Today' and (text() = 'Today' or . = 'Today')]</value>
      <webElementGuid>25c184a2-bc73-4de9-bd6b-9b01185a5051</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
