<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_txtpassword</name>
   <tag></tag>
   <elementGuidId>4dcce9db-2460-4b42-8961-867c776ba46c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#password-field</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='password-field']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5761b4c7-590a-46a4-aa04-8bb8b2e8f5dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>547a0489-18fb-4c20-8abe-1bccb0dd6cc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Your password</value>
      <webElementGuid>1883f04b-cbd4-4399-a74f-18888b0fcb0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>password-field</value>
      <webElementGuid>fe013170-9fd6-4308-9335-909588bfe79f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>05640f30-a7b1-4bcb-b945-91d3b57d52c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtpassword</value>
      <webElementGuid>71660ae9-0ba2-4b4a-b83a-881ce5c09e2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;password-field&quot;)</value>
      <webElementGuid>16d6b7d2-0a06-42af-a640-f1544a1d9da5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='password-field']</value>
      <webElementGuid>cd2398a4-edaf-4126-b12b-acba0d373183</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flash-message']/div[2]/div/div/div/input[3]</value>
      <webElementGuid>dac9c69c-e260-4b29-8599-7b1f4c9192fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>17bc0872-88c8-48ea-b16e-80b10c0b3d48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = 'Your password' and @id = 'password-field' and @name = 'txtpassword']</value>
      <webElementGuid>1a81e7f2-eedd-41af-97e8-5845c9fc6ca1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
