<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Verdana_note-editable</name>
   <tag></tag>
   <elementGuidId>0cae6252-854c-462a-bab6-ba116aaf2801</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.note-editable</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container-summernote73233']/div[2]/div[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>63fe867b-4f4b-4d80-9bd1-2167ae43019f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>note-editable</value>
      <webElementGuid>79b5ca26-c6e5-4b72-a1f2-82b7df476143</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>contenteditable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>892a14b9-cb24-4329-af06-f8724abdd681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container-summernote73233&quot;)/div[@class=&quot;note-editor&quot;]/div[@class=&quot;note-editable&quot;]</value>
      <webElementGuid>dac0336c-3c21-4014-b5d5-53ef3a6bb64e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container-summernote73233']/div[2]/div[6]</value>
      <webElementGuid>f01d7f3c-8d16-4a6b-a14d-fb8d7dae98dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[6]</value>
      <webElementGuid>30bebbab-ca09-445a-b336-eee08e57b954</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
