<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Setting_top-search</name>
   <tag></tag>
   <elementGuidId>c3c9a4a7-d56f-49d4-9e6f-ff15cec71d74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#top-search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='top-search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4c254b86-e744-4b15-9de0-04fdb219b69e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8c0378f5-9972-4463-9c0d-8e04adf3aac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>searchKeyPress(event,this,' + count + ' );</value>
      <webElementGuid>dd8f27f9-f3f6-4f6f-9902-639385825d11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search...</value>
      <webElementGuid>c1844d67-8e0a-4607-af28-9c50eaf9b151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>45ce842f-11e0-44e6-a47e-470c3828b2f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>top-search</value>
      <webElementGuid>dac526c1-d716-4065-aa40-a6e0c7e39c95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>top-search</value>
      <webElementGuid>04c4e8ae-a922-4064-97ab-9526d5850904</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top-search&quot;)</value>
      <webElementGuid>df789979-c08a-4c20-bbb5-353c1b78ef1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='top-search']</value>
      <webElementGuid>aae78ee8-ac9d-4038-a53b-4c51ca4e6ece</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='search-bar']/input</value>
      <webElementGuid>9339ce58-1a1b-4eb0-9194-78f17e8d235c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/input</value>
      <webElementGuid>7fed98c5-b97d-4cdd-93f8-201880b7d3c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Search...' and @name = 'top-search' and @id = 'top-search']</value>
      <webElementGuid>674941a2-14a1-4c1a-b7ee-eaf159ada9f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
