<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search_advbtninbound_table_010</name>
   <tag></tag>
   <elementGuidId>c28886b7-c683-48c3-a4dd-b07db8b670d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='advbtninbound_table_010']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#advbtninbound_table_010</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>849bfe5f-40ca-4860-890d-6b3e5ec9ff13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>advbtninbound_table_010</value>
      <webElementGuid>b036d59e-b95c-4b91-880f-bc738114dbc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-sm active</value>
      <webElementGuid>b9f01417-b2b1-4a4f-ada3-e1d5d807afa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3f0bf2cc-1950-499e-8f97-1e93cfb4bcac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;advbtninbound_table_010&quot;)</value>
      <webElementGuid>93b97800-2b40-4816-9a59-459d9fe5d67d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='advbtninbound_table_010']</value>
      <webElementGuid>1dd649fa-88bc-4dc1-bf78-343a5756050a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_inbound_table_010']/div/div[2]/div/div/div/div/div/button[2]</value>
      <webElementGuid>c5fd6821-0a83-4e59-af18-bad669bfa07a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Report Case'])[2]/following::button[2]</value>
      <webElementGuid>6fe7fb9d-446d-4bbf-91e4-3546e25fdd77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Closing Sales'])[4]/preceding::button[1]</value>
      <webElementGuid>d37e8bdd-a7e5-4159-bfaf-fc804f66440d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Channel'])[6]/preceding::button[1]</value>
      <webElementGuid>e13cbdcc-5802-42bb-a047-f2401cdd7f4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/div/div/div/div/div/button[2]</value>
      <webElementGuid>154274a3-bb06-4daa-b63f-5a9976c14d31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'advbtninbound_table_010' and @type = 'button']</value>
      <webElementGuid>d2615f51-c46c-402e-a422-abe0e3154aee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
