<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Periode_searchdatestartinbound_table_010</name>
   <tag></tag>
   <elementGuidId>5d5e1037-0196-4b73-b527-49d774aaa8c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='searchdatestartinbound_table_010']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#searchdatestartinbound_table_010</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>80312496-7e0b-445c-9673-6c524de46461</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchdatestartinbound_table_010</value>
      <webElementGuid>748dea30-ae06-4e22-aa67-3089b9cd4be8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control p-l-xs</value>
      <webElementGuid>4151a969-1d36-4e77-9a63-ad341d6f7afd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>18/07/2023</value>
      <webElementGuid>a2f91343-c290-4821-8d0b-f4fc29d175b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>675eef37-025c-4601-8848-74c82c4cc434</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchdatestartinbound_table_010&quot;)</value>
      <webElementGuid>e1e784e9-9771-49c8-910e-fea9c118eb5b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='searchdatestartinbound_table_010']</value>
      <webElementGuid>1dbad80c-0c3c-4051-b8ea-c30090762f75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='advfilterinbound_table_010']/div/div[4]/div/div/input</value>
      <webElementGuid>128f1ccc-e13d-4441-be95-bc55c32524d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>5299014f-c359-497f-a104-5b9d9cfead19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'searchdatestartinbound_table_010' and @type = 'text']</value>
      <webElementGuid>249d5426-2453-4337-9476-afcaecbab9a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
