<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Month</name>
   <tag></tag>
   <elementGuidId>bcfc247b-b288-4fcb-90c3-52d38ba1d8ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-searchperiodeinbound_table_010-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-searchperiodeinbound_table_010-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>41831d85-7912-449a-83d8-f8c0b8101938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>bc695a5f-e707-4629-aeb1-7220702a4adf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-searchperiodeinbound_table_010-container</value>
      <webElementGuid>ed63438d-9d49-4268-b3f1-95fee71ea491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Month</value>
      <webElementGuid>7ca5a109-90a9-4ebe-a9a9-a8b6dd133fee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Month</value>
      <webElementGuid>b575be0c-a182-4cf6-b77a-bfbff93465f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-searchperiodeinbound_table_010-container&quot;)</value>
      <webElementGuid>c204f0c8-3cbb-4055-984f-e3c3656697bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-searchperiodeinbound_table_010-container']</value>
      <webElementGuid>e987838e-d7ab-48db-8910-c9a319334733</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='advfilterinbound_table_010']/div/div[3]/span/span/span/span</value>
      <webElementGuid>0d3a5e69-1e4e-4b8f-9add-9ef13ae1e7a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Product'])[4]/following::span[6]</value>
      <webElementGuid>ec99d75e-1fd5-49fc-809f-f8d6308362bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Region'])[4]/following::span[12]</value>
      <webElementGuid>dc7d7b33-2a14-43d8-a761-d71495726033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Omni Team'])[5]/preceding::span[5]</value>
      <webElementGuid>2bab1a08-624e-466b-9f64-5b2f727f3e41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Region'])[6]/preceding::span[11]</value>
      <webElementGuid>d97ca027-4874-44b1-922a-6cd2528de3d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/span/span/span/span</value>
      <webElementGuid>65211604-ee4f-43a2-8661-bfbc5c505019</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-searchperiodeinbound_table_010-container' and @title = 'Month' and (text() = 'Month' or . = 'Month')]</value>
      <webElementGuid>b6ae68dd-2117-4294-afeb-72493df5258a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
