<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Periode_input-group-addon</name>
   <tag></tag>
   <elementGuidId>94d11142-7c07-4442-a65d-6f664025c0fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='advfilterinbound_table_010']/div/div[4]/div/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.input-group-addon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fbbb7bf5-94f6-4311-b8dd-87e38ff86caa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-group-addon</value>
      <webElementGuid>84a780d7-aab9-414b-a1b0-c9e6495a920b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;advfilterinbound_table_010&quot;)/div[@class=&quot;row no-margins&quot;]/div[@class=&quot;col-xs-4 col-sm-2 p-t-none p-r-xs p-b-xs p-l-none&quot;]/div[@class=&quot;form-group m-b-none&quot;]/div[@class=&quot;input-group date&quot;]/span[@class=&quot;input-group-addon&quot;]</value>
      <webElementGuid>6a8ac5fc-7cbf-4d33-bd13-319493459894</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='advfilterinbound_table_010']/div/div[4]/div/div/span</value>
      <webElementGuid>8cb36dd7-db03-4e46-a556-b600cc639d8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Periode'])[2]/following::span[3]</value>
      <webElementGuid>672bbc59-f32f-4d22-aa7e-f8c6126f96aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Product'])[4]/following::span[9]</value>
      <webElementGuid>338c572f-2c50-4c0c-858a-e99e0c85b843</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Omni Team'])[5]/preceding::span[2]</value>
      <webElementGuid>390fb39f-388f-467e-89d9-0d06000b738c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Region'])[6]/preceding::span[8]</value>
      <webElementGuid>c34ceceb-2143-455b-8448-a232779591e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div[4]/div/div/span</value>
      <webElementGuid>fa81dcd2-6b82-48ec-8bd2-9d5b2da094a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
