<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Hima Putriani - 4936906709694016</name>
   <tag></tag>
   <elementGuidId>0fd471b2-23e9-4020-9ee1-1470307337ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='colcase3search_table_010Id525487']/td[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.text-wrapper.va-middle.requester</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>893a5491-0818-4399-a792-bb9c4179deac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-wrapper va-middle requester</value>
      <webElementGuid>bb0ab091-309a-4c06-b0e6-4bf83ed3ef4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hima Putriani - 4936906709694016</value>
      <webElementGuid>31a84d68-f385-419f-ac3c-1b6f8df2ad5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;colcase3search_table_010Id525487&quot;)/td[@class=&quot;text-wrapper va-middle requester&quot;]</value>
      <webElementGuid>fa64cb03-452e-48df-98cd-800248c54a9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='colcase3search_table_010Id525487']/td[3]</value>
      <webElementGuid>c91da7c5-f8ea-4dac-ad3f-a9c05a69e1fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time to Response'])[1]/following::td[3]</value>
      <webElementGuid>72d9ecca-a593-49b0-98d3-334c3550f331</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[2]/following::td[3]</value>
      <webElementGuid>22eb096a-04ac-4b2d-9be5-eaf54ce8dc24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]</value>
      <webElementGuid>fc0cc168-7fad-4a45-be1b-e0dff28a94b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Hima Putriani - 4936906709694016' or . = 'Hima Putriani - 4936906709694016')]</value>
      <webElementGuid>283c49d4-fe73-47f6-844a-7f3fa122ff65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
