<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search_advbtninbound_table_010</name>
   <tag></tag>
   <elementGuidId>ff3af972-16a7-4d70-95ec-7795f4863705</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='advbtninbound_table_010']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#advbtninbound_table_010</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ff5a9fd8-4cae-42af-b9af-2055c820df86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>advbtninbound_table_010</value>
      <webElementGuid>a9bc06ec-6989-4d73-8048-3610be4d17ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-sm active</value>
      <webElementGuid>04d44d15-c140-45c4-a8af-2e5e4f8f31f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>af901cff-c193-4267-aeb9-8d555dc0d4f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;advbtninbound_table_010&quot;)</value>
      <webElementGuid>601e4963-495d-4ba4-84a8-18c5aa226dac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='advbtninbound_table_010']</value>
      <webElementGuid>ca4d3f8a-18eb-4e7d-89e1-b8105fc9e58b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_inbound_table_010']/div/div[2]/div/div/div/div/div/button[2]</value>
      <webElementGuid>086361f4-84c3-436e-bc68-a0231943e011</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Report Case'])[2]/following::button[2]</value>
      <webElementGuid>ed083835-7d47-40e6-87bb-7309399049fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Closing Sales'])[3]/preceding::button[1]</value>
      <webElementGuid>de19831b-fd9d-43c1-899e-9969215703e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Channel'])[4]/preceding::button[1]</value>
      <webElementGuid>7ad99af1-a4f8-4dea-a499-c93c2ed9d03c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/button[2]</value>
      <webElementGuid>57585966-455e-4120-989b-774c82a3ab7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'advbtninbound_table_010' and @type = 'button']</value>
      <webElementGuid>fe136fa1-5a8b-445b-9491-fc01faf71b63</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
