<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search</name>
   <tag></tag>
   <elementGuidId>a8739329-a1cd-494f-8841-73d0a59a0a92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='searchinbound_table_010']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#searchinbound_table_010</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7fc11f46-49d7-437e-b75a-253e2b4eeb46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchinbound_table_010</value>
      <webElementGuid>b02b299f-848d-4c80-b843-daf94db3ff1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>55ac4b31-3559-4209-831b-651a750565c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-sm animated fadeInRight</value>
      <webElementGuid>d011a38f-b948-46cd-a8ae-b63d10397253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6a3b61b8-b0d2-43cb-a217-a0c6ee9dba66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Search data</value>
      <webElementGuid>1ab0f960-241c-4f55-8ddb-9b2b4d0fa300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
									 Search
								</value>
      <webElementGuid>1b136457-4b07-43e1-9937-75da4fca6ab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchinbound_table_010&quot;)</value>
      <webElementGuid>3b5ac7cb-9580-447c-b95a-a2fbb4283789</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='searchinbound_table_010']</value>
      <webElementGuid>c1998f66-79bc-48ff-9f8e-05a077314be6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_inbound_table_010']/div/div[2]/div/div/div/div/div/button</value>
      <webElementGuid>d398b8d7-8a8e-4855-b8d3-83560a250951</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Report Case'])[2]/following::button[1]</value>
      <webElementGuid>4c39f495-6dca-406e-b799-f78a5b7ebe66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[2]/following::button[1]</value>
      <webElementGuid>43e94ce9-92e1-4a1f-8174-d3eb0048e025</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Closing Sales'])[3]/preceding::button[2]</value>
      <webElementGuid>18014014-30e6-4dfc-b4ba-be5a2e9c07eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Channel'])[4]/preceding::button[2]</value>
      <webElementGuid>75bc2e6e-8ea6-4065-bc1a-5dd8d67d30f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/button</value>
      <webElementGuid>54640c8d-295a-43fc-ba15-650287c839de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'searchinbound_table_010' and @name = 'search' and @type = 'button' and @title = 'Search data' and (text() = '
									 Search
								' or . = '
									 Search
								')]</value>
      <webElementGuid>6b645e63-f9ba-48e0-be26-848bdc0a90a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
