<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Today</name>
   <tag></tag>
   <elementGuidId>c24eaf8a-0176-494e-94d8-4bfba647ca2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-searchperiodeinbound_table_010-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-searchperiodeinbound_table_010-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e75c0a46-98f4-4d60-bfca-22d0543ea44c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>62cd17c6-fbcb-4e9a-b611-5e1238cd8a6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-searchperiodeinbound_table_010-container</value>
      <webElementGuid>dbf3f969-56ef-49dc-8870-d123cc2d9167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Today</value>
      <webElementGuid>e4e242d7-c38d-4344-ac28-cdb9cd3e7de9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Today</value>
      <webElementGuid>e074ef70-de87-4568-a100-b253dba40696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-searchperiodeinbound_table_010-container&quot;)</value>
      <webElementGuid>6b857f0c-4044-4e00-b40c-30b577976bd2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-searchperiodeinbound_table_010-container']</value>
      <webElementGuid>c04aeef1-8047-4a20-98bc-3f8ef1623f9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='advfilterinbound_table_010']/div/div[3]/span/span/span/span</value>
      <webElementGuid>35163987-ca2a-47ef-82a2-f50e2f8a7a03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Product'])[4]/following::span[6]</value>
      <webElementGuid>f8a4e00a-3021-4e0c-b116-f45529706428</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Region'])[4]/following::span[12]</value>
      <webElementGuid>e213ccb1-2eb4-40d5-9c58-1c2752ae68b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Omni Team'])[5]/preceding::span[5]</value>
      <webElementGuid>3583ccfa-f514-427a-8d5a-86bbaa1879e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Region'])[6]/preceding::span[11]</value>
      <webElementGuid>0cbe5545-8753-4dcb-be75-51b730be5308</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/span/span/span/span</value>
      <webElementGuid>475529cb-3b24-4c87-860b-7dc53e49e68f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-searchperiodeinbound_table_010-container' and @title = 'Today' and (text() = 'Today' or . = 'Today')]</value>
      <webElementGuid>5fe5efd1-5c6a-4203-a9bf-0ff776fc52e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
