<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Month</name>
   <tag></tag>
   <elementGuidId>1ee02566-7c08-4d9b-9413-073c1d7cea54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-searchperiodeinbound_table_010-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-searchperiodeinbound_table_010-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>684e8560-1c36-4b96-9515-3f3f5e396689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>ab867301-c699-4d20-91e1-4169145afbe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-searchperiodeinbound_table_010-container</value>
      <webElementGuid>9d6d73c2-98c5-4e45-b478-4abd03430235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Month</value>
      <webElementGuid>6d302521-b6b9-47bb-963d-3cc9231e85c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Month</value>
      <webElementGuid>6b051f6a-8d3c-447c-aa99-f81e45690f2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-searchperiodeinbound_table_010-container&quot;)</value>
      <webElementGuid>af007974-0ad5-46d8-b866-cc75eb160090</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-searchperiodeinbound_table_010-container']</value>
      <webElementGuid>caa25f85-acea-4b0d-96ec-496de47704a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='advfilterinbound_table_010']/div/div[3]/span/span/span/span</value>
      <webElementGuid>9a6a5df6-d4d8-4d1b-b630-7f966804bac2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Product'])[4]/following::span[6]</value>
      <webElementGuid>333c41f6-2e72-4fea-8fc0-b397b4dc9646</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Region'])[4]/following::span[12]</value>
      <webElementGuid>fb84a261-9b3e-4da3-ae8d-a5ad77f6cff9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Omni Team'])[5]/preceding::span[5]</value>
      <webElementGuid>43cd7be5-4736-4530-952f-b5f167cc9a6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Region'])[6]/preceding::span[11]</value>
      <webElementGuid>b92cd45e-cd77-464a-856f-11cea93b0694</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/span/span/span/span</value>
      <webElementGuid>799c2e7b-8072-4470-a606-fcd051eb32c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-searchperiodeinbound_table_010-container' and @title = 'Month' and (text() = 'Month' or . = 'Month')]</value>
      <webElementGuid>c3522f8f-f444-430a-8a02-d835c9135ecd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
