<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Case Detail</name>
   <tag></tag>
   <elementGuidId>fbdcd33a-67c2-4472-b39b-b8aa42484d27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//ul[@id='ulNavSecondLevel']/li/a)[27]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.p-l-sm.li-item-side-menu.active > #ulNavSecondLevel > li.li-item-subside-menu > a.a-item-subside-menu</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c0c90eb7-dff8-46b4-8b34-599b23de810d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#/report/CaseDetail/inbound</value>
      <webElementGuid>b780ec28-8cab-42b1-b438-fb3cbdec46f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-item-subside-menu</value>
      <webElementGuid>ad59f900-d1e6-4115-b3fe-6dc685d0c5a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Case Detail  </value>
      <webElementGuid>fb1b5960-18e0-4773-9cae-64534226541a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;side-menu&quot;)/li[@class=&quot;p-l-sm li-item-side-menu active&quot;]/ul[@id=&quot;ulNavSecondLevel&quot;]/li[@class=&quot;li-item-subside-menu&quot;]/a[@class=&quot;a-item-subside-menu&quot;]</value>
      <webElementGuid>83820d4b-fef4-42bc-89b7-04478ba7c813</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//ul[@id='ulNavSecondLevel']/li/a)[27]</value>
      <webElementGuid>aa4b2de2-ce27-4959-823f-fd872d28de60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Case Detail')]</value>
      <webElementGuid>22956c45-8073-4704-b29c-f73b8731a651</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Report Case'])[2]/following::a[1]</value>
      <webElementGuid>6c3a1275-341d-456c-adae-b515c91b7bc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Report Case'])[1]/following::a[1]</value>
      <webElementGuid>3e03437f-6887-41cc-87ca-77789c65caa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Case Internal'])[1]/preceding::a[1]</value>
      <webElementGuid>0fed94d9-e4fd-4257-8808-96c9b2fbbdfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Report Pengaduan'])[1]/preceding::a[2]</value>
      <webElementGuid>5c3ec6e9-dce8-4de5-ad49-7822c25069d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Case Detail']/parent::*</value>
      <webElementGuid>3914df05-5ef9-4cb4-a27c-a4b6613aa3bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#/report/CaseDetail/inbound')]</value>
      <webElementGuid>6f143323-f015-4b7f-9f7f-ad5c9d0ddd1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[9]/ul/li/a</value>
      <webElementGuid>3690a310-ce13-4f37-99ca-9b43f9f5edf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#/report/CaseDetail/inbound' and (text() = '  Case Detail  ' or . = '  Case Detail  ')]</value>
      <webElementGuid>3f306534-df3c-42c6-ac55-1e97a22676b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
