<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_refresh_advbtna5tqd</name>
   <tag></tag>
   <elementGuidId>ce336669-1205-448d-b867-27cb8008f05a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='advbtna5tqd']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#advbtna5tqd</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>36b69af3-c2ac-4a88-b4db-40d4cf6c9b7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>advbtna5tqd</value>
      <webElementGuid>b24c0699-a351-432b-b522-f242fe5f8689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-white btn-sm </value>
      <webElementGuid>6bce10ba-e366-449d-880d-5f6543386331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>22d9481c-ff8a-4003-a69f-23c893f426c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;advbtna5tqd&quot;)</value>
      <webElementGuid>dbd741b9-e00b-429f-9052-448b40ae88c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='advbtna5tqd']</value>
      <webElementGuid>86a10d26-e4fe-449e-9c40-18c1802ff150</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashletFilter']/div/div/div[2]/div/div/div[2]/div/button[2]</value>
      <webElementGuid>0d579c89-d470-4101-a3aa-27fdf6aaea35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This Month'])[1]/preceding::button[2]</value>
      <webElementGuid>d89cef72-cae7-4f3c-864a-06576da4b717</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/button[2]</value>
      <webElementGuid>18de3d77-f80b-4805-9a35-eebea404eae9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'advbtna5tqd' and @type = 'button']</value>
      <webElementGuid>58b32d37-036d-4974-8e9c-76e696c8df61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
