<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_refresh_advbtn3t76a</name>
   <tag></tag>
   <elementGuidId>9d278316-014f-4f96-9b28-45686e2a4b30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='advbtn3t76a']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#advbtn3t76a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a4f9eab1-734d-44cc-82bf-085edff2ec3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>advbtn3t76a</value>
      <webElementGuid>182b9071-fb87-44d4-8ee5-d2d88a10448e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-white btn-sm </value>
      <webElementGuid>72d09ffe-607f-438f-9fa7-f458b4ec0be0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c5442d88-0059-47d3-a09b-2eb17387d80c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;advbtn3t76a&quot;)</value>
      <webElementGuid>1dadd8d7-631a-42b4-80f5-76c45b154610</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='advbtn3t76a']</value>
      <webElementGuid>b55b6b94-dbbf-4368-b795-9223844c6ed2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashletFilter']/div/div/div[2]/div/div/div[2]/div/button[2]</value>
      <webElementGuid>668cc616-51c4-4e90-96ad-a49d8525b822</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This Month'])[1]/preceding::button[2]</value>
      <webElementGuid>20205a9c-e2fb-4465-bca8-2784b4e16139</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/button[2]</value>
      <webElementGuid>20d4dd86-a620-4d75-a0d7-454f302f6e1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'advbtn3t76a' and @type = 'button']</value>
      <webElementGuid>fb425124-c046-4c78-8021-3d78d399bfae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
