<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_This Month</name>
   <tag></tag>
   <elementGuidId>3c2e3e2e-53bb-4f39-b557-e3fd1844520e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='searchdatepick02cw3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#searchdatepick02cw3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>aa899655-f5df-49b0-a2c1-91df5c2e7b49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchdatepick02cw3</value>
      <webElementGuid>2add462e-862d-420f-a088-6757987dcfee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-l-sm p-r-xs</value>
      <webElementGuid>101facca-b623-4fbc-a12d-7f270cf2d51a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>290afcda-a6d5-457e-8dea-1ab81d1afb77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placement</name>
      <type>Main</type>
      <value>right</value>
      <webElementGuid>a7e07836-5d7f-4960-91e9-a048cc740d53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>This Month</value>
      <webElementGuid>c6c14026-ab5d-4802-8f1a-a479005db501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-title</name>
      <type>Main</type>
      <value>This Month</value>
      <webElementGuid>aff9005d-e6bb-475d-b71a-87cee5c13859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datestart</name>
      <type>Main</type>
      <value>01/07/2023</value>
      <webElementGuid>c30ed40a-42fe-40ed-87f8-ce473b6b310c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dateend</name>
      <type>Main</type>
      <value>24/07/2023</value>
      <webElementGuid>c61278f8-3107-4387-b0e9-d740481433bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>This Month</value>
      <webElementGuid>8dbe0427-a58f-441f-86ac-f75a9b41ec83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchdatepick02cw3&quot;)</value>
      <webElementGuid>7cbd24b9-021e-4f75-b652-e188c28fd54f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='searchdatepick02cw3']</value>
      <webElementGuid>f0215c66-5a82-4807-913e-a19c67a3fb83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='searchDateReport02cw3']/b/span</value>
      <webElementGuid>4f430841-c357-422f-bf54-e156677d2c81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Team'])[3]/preceding::span[1]</value>
      <webElementGuid>ab531135-95e4-46ff-8532-07eded07a280</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Omni Team'])[3]/preceding::span[7]</value>
      <webElementGuid>42e8c394-4377-4176-bdea-f54fd80fcf2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div[2]/div/div/div/div/button/b/span</value>
      <webElementGuid>bfbebfae-db7d-426d-adb4-2565c221a817</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'searchdatepick02cw3' and @title = 'This Month' and (text() = 'This Month' or . = 'This Month')]</value>
      <webElementGuid>ee817706-949a-49f6-9709-bacf6bbb6400</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
