<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search</name>
   <tag></tag>
   <elementGuidId>baf25fdf-625b-4b6b-bbda-fc99e237a051</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='searchbtna5tqd']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#searchbtna5tqd</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>83358e27-6f21-4e27-b55a-d540f128a45f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-block</value>
      <webElementGuid>4f6909f1-c49c-48c3-aeca-a951dd39adde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchbtna5tqd</value>
      <webElementGuid>0953a772-5b52-4acd-a08d-fcbd27ace39c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fbbc5bd5-0bb9-4ae4-b181-31068ff4a53e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 
							Search						</value>
      <webElementGuid>66056e53-a16a-43ea-b793-1966e918e83b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchbtna5tqd&quot;)</value>
      <webElementGuid>6ad952b0-f60f-492e-8352-bf17cc6b8bd1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='searchbtna5tqd']</value>
      <webElementGuid>b1163622-af91-4d2d-8a16-31862c1468ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='tab-3']/div[3]/div[2]/button)[2]</value>
      <webElementGuid>4ead72e2-595b-4e7b-bb59-ae21cd51d258</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset Filter'])[2]/following::button[1]</value>
      <webElementGuid>36f0349e-4e3c-450d-8f32-11f9c4015ecd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Branch'])[2]/following::button[2]</value>
      <webElementGuid>b1b77d64-ea93-4d5b-8b87-3854b8f584e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Report General'])[1]/preceding::button[1]</value>
      <webElementGuid>d72e6025-742b-4a39-bbea-4e61e30664cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Now'])[1]/preceding::button[1]</value>
      <webElementGuid>159d4395-d0a8-458a-9934-4966d6da45fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div[3]/div[2]/button</value>
      <webElementGuid>709770cd-41d9-4dcb-9050-c811ef21595f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'searchbtna5tqd' and @type = 'button' and (text() = ' 
							Search						' or . = ' 
							Search						')]</value>
      <webElementGuid>4adbc9d1-6fa0-4802-a10a-99437665a152</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
