<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_refresh_advbtnoqyzn</name>
   <tag></tag>
   <elementGuidId>00fcd80b-1cce-4553-a6e8-e79847b3ad3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='advbtnoqyzn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#advbtnoqyzn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c3d2d8b2-3d56-470c-8318-4c70e91c51a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>advbtnoqyzn</value>
      <webElementGuid>ce76cec1-6963-46f7-8930-d1963cfa3436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-white btn-sm </value>
      <webElementGuid>24c3a404-aea8-4de2-8dc5-dfef947e6790</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9b1548a3-0450-4996-8700-1bc04f0a1759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;advbtnoqyzn&quot;)</value>
      <webElementGuid>ca50e676-c4fe-45ed-8bc5-ef1869be42ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='advbtnoqyzn']</value>
      <webElementGuid>f5bf72d3-1dcb-4dc5-9cd6-18be9279f645</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashletFilter']/div/div/div[2]/div/div/div[2]/div/button[2]</value>
      <webElementGuid>c4df15cb-1ca1-4ccd-ba4e-455ec4144b33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This Month'])[1]/preceding::button[2]</value>
      <webElementGuid>bc2fb5c9-fff3-4b87-817e-5ff925aaf19f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/button[2]</value>
      <webElementGuid>6742769b-f27e-4c7b-b994-ef3bc0b617c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'advbtnoqyzn' and @type = 'button']</value>
      <webElementGuid>15820112-e90b-460e-9365-52d715ff7ff0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
