<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_General Dashboard</name>
   <tag></tag>
   <elementGuidId>b0b5399f-38aa-4b4c-a2a0-2ea8b9b8ccc3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='side-menu']/li[8]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5abf9ae5-0eb8-40a1-9aaf-a9dfb5cedfe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#/dashboard/General/All</value>
      <webElementGuid>3783f005-8098-46a7-889e-0e4302d40d6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>3127889a-3bd2-45c0-ba25-1b3d0219fff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placement</name>
      <type>Main</type>
      <value>right</value>
      <webElementGuid>7a9378f6-d583-41dc-9b49-5902bca21e09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-title</name>
      <type>Main</type>
      <value> General Dashboard </value>
      <webElementGuid>dd2b1299-93fa-4990-a549-41bef862ce62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-item-side-menu</value>
      <webElementGuid>4ba66b3f-70f8-4f54-8f98-9096552c4299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  General Dashboard </value>
      <webElementGuid>33430070-9e09-4b97-aaf4-c4264778947a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;side-menu&quot;)/li[@class=&quot;p-l-sm li-item-side-menu&quot;]/a[@class=&quot;a-item-side-menu&quot;]</value>
      <webElementGuid>f10c405d-5c35-44d3-8623-b8ee5be50c2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='side-menu']/li[8]/a</value>
      <webElementGuid>bba71ed1-5b92-48a3-95fc-ea4b6295ae50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List Case Win'])[1]/following::a[1]</value>
      <webElementGuid>631bfb4e-440e-42ab-b4c9-c0cbc4e45099</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List Case Prospect'])[1]/following::a[2]</value>
      <webElementGuid>b77ffc74-e2b2-425d-ad4a-728e1d97706c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='General Dashboard'])[2]/preceding::a[1]</value>
      <webElementGuid>b5467a5a-d969-40e2-be3e-aebfc20389ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#/dashboard/General/All')]</value>
      <webElementGuid>e2bf0e60-8f6f-4802-9179-e6c3351cb1d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/a</value>
      <webElementGuid>675e013f-ed7a-4c95-a75b-7aa4db4765d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#/dashboard/General/All' and (text() = '  General Dashboard ' or . = '  General Dashboard ')]</value>
      <webElementGuid>c9ec915e-a4c7-44e1-a001-38b9a365f40e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
