<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search</name>
   <tag></tag>
   <elementGuidId>ac0534b7-0445-41dd-aae9-a79116c2e904</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='searchbtnslaagent_table_010']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#searchbtnslaagent_table_010</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cb81a132-27c5-4ac6-97bd-aacfcc99a0c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>3a1bb7be-cb4f-434b-be6e-c79d1c25ed32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchbtnslaagent_table_010</value>
      <webElementGuid>23685e01-b1ea-4ea7-a7c2-2ad774e0a950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-sm animated fadeInRight</value>
      <webElementGuid>4501c66e-8fe1-4ce0-b9b0-120e624ac0bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>eb539d28-b4c7-4195-b6d3-c706ece9d7c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
									 Search
								</value>
      <webElementGuid>bdcb4e42-18ae-416b-a261-9b619263074e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchbtnslaagent_table_010&quot;)</value>
      <webElementGuid>feee94e9-f478-4120-b567-919dc65d0989</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='searchbtnslaagent_table_010']</value>
      <webElementGuid>e5e933e8-6322-4b98-bdd0-55fa83df61b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='scroll_content_slaslaagent_table_010']/div/div/div/div/div/div/button</value>
      <webElementGuid>6e372453-aa3d-4b11-8979-774ec8cd6b3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Report SLA Agent'])[1]/following::button[1]</value>
      <webElementGuid>0bab2449-21d1-443a-96cd-5db5277b18f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Case by Resolution'])[1]/following::button[1]</value>
      <webElementGuid>7df4f03b-c106-4446-b42b-1b6525ac8f2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agent'])[7]/preceding::button[2]</value>
      <webElementGuid>f5815f07-edd2-439c-86cb-784e30e73b3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lurah'])[2]/preceding::button[2]</value>
      <webElementGuid>1539110f-512a-4023-a023-697f324f10ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div[2]/div/div/div/div/div/div/div/button</value>
      <webElementGuid>0346b883-085e-476a-bcf4-cc84d1cfc0bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'search' and @id = 'searchbtnslaagent_table_010' and @type = 'button' and (text() = '
									 Search
								' or . = '
									 Search
								')]</value>
      <webElementGuid>daad59de-425c-4e6c-bb1d-ff65462b25de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
