<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search_advbtnslaagent_table_010</name>
   <tag></tag>
   <elementGuidId>30cb0dd6-924b-4210-9e7f-600ec364762d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='advbtnslaagent_table_010']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#advbtnslaagent_table_010</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2fd53f31-8733-4ca5-a078-90ea3ef7c558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>advbtnslaagent_table_010</value>
      <webElementGuid>94b1b32c-3597-4408-9a76-400e158d9959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-sm active</value>
      <webElementGuid>30fdf68d-75ec-495b-b7f7-bbc0d4791485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dc53f293-ed5c-4ed6-9f97-ce64fbd1c8ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;advbtnslaagent_table_010&quot;)</value>
      <webElementGuid>de6d9383-71df-4d5f-8c82-650b022255a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='advbtnslaagent_table_010']</value>
      <webElementGuid>7a20c16c-af13-42e5-8476-7b20b350c067</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='scroll_content_slaslaagent_table_010']/div/div/div/div/div/div/button[2]</value>
      <webElementGuid>b3ec9255-fcc0-4e0d-a56a-30215aea69a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Report SLA Agent'])[1]/following::button[2]</value>
      <webElementGuid>c30bafa9-5469-4a80-a57e-e787cd4d2741</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agent'])[7]/preceding::button[1]</value>
      <webElementGuid>eb9556d4-e4f6-43e5-b9ce-cfd574db3478</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lurah'])[2]/preceding::button[1]</value>
      <webElementGuid>54123f5e-3847-457f-9715-56716920987c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div[2]/div/div/div/div/div/div/div/button[2]</value>
      <webElementGuid>4cdd59ef-73b3-4802-bb4a-c0fc6a9af67d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'advbtnslaagent_table_010' and @type = 'button']</value>
      <webElementGuid>68022619-422f-4c2e-8c34-c29a83e705d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
