<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Today</name>
   <tag></tag>
   <elementGuidId>9435ae59-0a06-4f6f-80d2-09c86b9f913b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-searchperiodeslaagent_table_010-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-searchperiodeslaagent_table_010-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>175913a5-2367-46cd-9143-44bf32347d5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>d46cdfb5-3e83-4557-bae9-7afc0d1d5a8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-searchperiodeslaagent_table_010-container</value>
      <webElementGuid>3576bd6f-e50c-4f69-9c7e-d20055f8c2d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Today</value>
      <webElementGuid>99989c29-0a4a-4513-9dc5-dad6f0c6ccc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Today</value>
      <webElementGuid>a2822cb7-b235-4cb3-bff7-c020e44784ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-searchperiodeslaagent_table_010-container&quot;)</value>
      <webElementGuid>74837ade-5954-4423-ae34-7d286853e7ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-searchperiodeslaagent_table_010-container']</value>
      <webElementGuid>c2488b5e-eee0-4f7c-932d-8776fdb035a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='advfilterslaagent_table_010']/div[3]/span/span/span/span</value>
      <webElementGuid>cffd1d71-517f-47dd-89ff-21f50783c0bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Product'])[10]/following::span[6]</value>
      <webElementGuid>53d57751-73c2-423e-a8f7-baca580f65cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Region'])[14]/following::span[12]</value>
      <webElementGuid>0b358e9b-5a77-49ff-9a91-63653dc4f630</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Processing...'])[3]/preceding::span[5]</value>
      <webElementGuid>ce9bbe67-f670-46b4-970e-fd5ef086ac2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copy'])[3]/preceding::span[5]</value>
      <webElementGuid>bf02cb69-97b8-49d0-afca-5191f20a40a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[2]/div[3]/span/span/span/span</value>
      <webElementGuid>34ac9658-2f71-40c7-9cdd-572ac73ecf74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-searchperiodeslaagent_table_010-container' and @title = 'Today' and (text() = 'Today' or . = 'Today')]</value>
      <webElementGuid>13c292e3-d4b7-4efe-8fee-6c48ef8208c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
