<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Report SLA</name>
   <tag></tag>
   <elementGuidId>1d542a1a-018e-482f-aa43-a8e1a16bfb71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='side-menu']/li[11]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f30c445b-e758-4c6a-91b0-9ae8fd53ae3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#/report/Sla/Report/mainAllSLA</value>
      <webElementGuid>0ff73b73-94ba-4682-848d-f409f65a072d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>028059b1-dcf6-42ca-a2bf-e48bde0a2f47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placement</name>
      <type>Main</type>
      <value>right</value>
      <webElementGuid>4af6ce97-d78e-46ba-9cc5-c01e5bfcae46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-title</name>
      <type>Main</type>
      <value> Report SLA </value>
      <webElementGuid>172fa9c4-60a8-475b-8ed8-363a3be2c916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-item-side-menu</value>
      <webElementGuid>ae61aaa5-a161-41e5-87dc-bbe879de8b6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip342581</value>
      <webElementGuid>99df8f0b-96fc-4d42-b844-3b5bb79436b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Report SLA </value>
      <webElementGuid>dc3d4ef5-b075-4507-a766-a2aca5afe249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;side-menu&quot;)/li[@class=&quot;p-l-sm li-item-side-menu&quot;]/a[@class=&quot;a-item-side-menu&quot;]</value>
      <webElementGuid>233412b6-3cfb-4ed0-b9dc-26b349d293f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='side-menu']/li[11]/a</value>
      <webElementGuid>f7b3a8c7-d30e-414c-a76c-75526eb77458</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Outbound By Subject'])[1]/following::a[1]</value>
      <webElementGuid>df617898-dc80-4cf0-915f-6179bdb33a94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Outbound By Status'])[1]/following::a[2]</value>
      <webElementGuid>33a221c7-451b-4871-9d63-ce17f5c90f60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Report SLA'])[2]/preceding::a[1]</value>
      <webElementGuid>1de455f1-323d-42a1-a5e5-6c5d2ea2e830</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#/report/Sla/Report/mainAllSLA')]</value>
      <webElementGuid>5b7a6a06-c591-421f-9ffd-953969f4ff62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[11]/a</value>
      <webElementGuid>67f3e0b9-6533-4eaf-9f53-ae8f241a38b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#/report/Sla/Report/mainAllSLA' and (text() = '  Report SLA ' or . = '  Report SLA ')]</value>
      <webElementGuid>f8688673-343b-471f-9bda-2245e6ae84d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
