<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search</name>
   <tag></tag>
   <elementGuidId>71c6d1bf-04d1-4ed1-acec-7c3b3285c1da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='searchbtn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#searchbtn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7cbd91e8-580b-4e3a-89d1-c163e3789b52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>c916c678-bbb2-4ed0-ad3c-351ddda5b0ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchbtn</value>
      <webElementGuid>f11eb87b-14f2-4848-b399-b1d50116f14d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-sm animated fadeInRight</value>
      <webElementGuid>e06782a8-98cb-4df3-870b-5c20327d22b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>078499d2-818b-4359-987f-9dd17bd89fd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
									 Search
								</value>
      <webElementGuid>90bcbda6-3b0f-4578-ade9-0868c5ab54e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchbtn&quot;)</value>
      <webElementGuid>86962838-d81c-4c04-94ac-94bf696751e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='searchbtn']</value>
      <webElementGuid>51495d94-42c6-4529-a381-b76464db642e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_inbound_detail_table_010']/div/div[2]/div/div/div/div/div/button</value>
      <webElementGuid>8b7c8a23-d436-4232-b5cd-138feedad23c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Report Case'])[3]/following::button[1]</value>
      <webElementGuid>bb6d108d-a75c-4e99-98f0-a82180163168</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 1 to 10 of 24 entries'])[1]/following::button[1]</value>
      <webElementGuid>24ef6209-5bb2-4ea9-8e6f-3fa34ccbe10d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Message Type'])[2]/preceding::button[2]</value>
      <webElementGuid>0c7ea8f3-b2e7-4ba8-9c43-30bc2ce514e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Media'])[2]/preceding::button[2]</value>
      <webElementGuid>f2208a1f-5a41-4bd2-b04b-56daab0f5101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/form/div/div[2]/div/div/div/div/div/button</value>
      <webElementGuid>2739c415-6e66-457d-8ce8-4ea012aff157</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'search' and @id = 'searchbtn' and @type = 'button' and (text() = '
									 Search
								' or . = '
									 Search
								')]</value>
      <webElementGuid>81a65f75-4de8-4c03-8b8f-bac85f6612a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
