<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_refresh_advbtnvr1zp</name>
   <tag></tag>
   <elementGuidId>8c3a3082-4e7d-4647-8ddf-c1e21c8d25e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='advbtnvr1zp']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#advbtnvr1zp</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b797a869-449d-417d-8c14-fdf1e2228935</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>advbtnvr1zp</value>
      <webElementGuid>aecc7dcd-90d3-4afb-a7ff-08b904efec49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-white btn-sm </value>
      <webElementGuid>8f612d39-5c45-4e24-9204-077ed8fa4874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d5480390-eadf-4ec6-abd2-17125f3a2170</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;advbtnvr1zp&quot;)</value>
      <webElementGuid>6358212e-16bd-4d1d-b668-ea8485231c7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='advbtnvr1zp']</value>
      <webElementGuid>fb1563bf-0756-48de-84dc-51268586b551</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashletFilter']/div/div/div[2]/div/div/div[2]/div/button[2]</value>
      <webElementGuid>48b15754-c1e5-4f15-908d-112867a86a86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This Month'])[1]/preceding::button[2]</value>
      <webElementGuid>2545c0f6-23b2-4890-abcb-e2cafb44b581</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/button[2]</value>
      <webElementGuid>bc97f51d-6ee1-401d-9af4-9fc425736e8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'advbtnvr1zp' and @type = 'button']</value>
      <webElementGuid>8beaf8ee-ae15-484d-87f7-0a4f85c8d1ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
