<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_refresh_advbtnst829</name>
   <tag></tag>
   <elementGuidId>fa6330dc-5998-4419-adfd-1a22d19db9bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='advbtnst829']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#advbtnst829</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8ad2a218-4989-4dcb-bd4b-f735414e51c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>advbtnst829</value>
      <webElementGuid>2e015eb9-7790-40a2-bbe1-01e8f471d112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-white btn-sm </value>
      <webElementGuid>89f8084d-4dba-4800-845a-7f5b0cb07ad9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d7d076a8-4361-4b54-b13c-9c1a3f08beba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;advbtnst829&quot;)</value>
      <webElementGuid>497ac108-f667-478c-b92f-3a4d2f2f07ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='advbtnst829']</value>
      <webElementGuid>6d750585-1c0f-4ec8-8591-ad552e191099</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashletFilter']/div/div/div[2]/div/div/div[2]/div/button[2]</value>
      <webElementGuid>c2e0c04b-235b-4a49-9461-ec3cbe343420</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This Month'])[1]/preceding::button[2]</value>
      <webElementGuid>f6c27ed1-c229-4f86-a9a8-0750d7ff24b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/button[2]</value>
      <webElementGuid>1b6d7956-8263-4b30-96e2-24fc740aa621</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'advbtnst829' and @type = 'button']</value>
      <webElementGuid>b90bf9c3-d485-46df-bc2a-787dd5a07772</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
