<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search_advbtntab_report_agent_activity</name>
   <tag></tag>
   <elementGuidId>ec17c6b3-3596-4ec7-a750-c256113e996a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='advbtntab_report_agent_activity']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#advbtntab_report_agent_activity</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a2da42f2-cf5d-4c68-bf52-bad1e6d72c80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>advbtntab_report_agent_activity</value>
      <webElementGuid>1be3289c-b43f-4355-98bd-a80427355c31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-sm active</value>
      <webElementGuid>648d2d36-ed35-4e60-a3cc-7de7d42fa05b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7e7ee5cb-1df5-409d-bac0-cfa27f153aae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;advbtntab_report_agent_activity&quot;)</value>
      <webElementGuid>fda3b54a-dcce-4725-ae86-4973ab1b4377</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='advbtntab_report_agent_activity']</value>
      <webElementGuid>02f529e6-e8b9-444e-bcac-b1f436e36c21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_tab_report_agent_activity']/div/div/div/div/div/div/div/button[2]</value>
      <webElementGuid>426a9422-07b0-4502-910b-75b4e6035fcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Report Agent Activity'])[1]/following::button[2]</value>
      <webElementGuid>21bbc504-b06e-46b3-8134-5c8fff40bac4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Team'])[20]/preceding::button[1]</value>
      <webElementGuid>c80d7ae4-1d3d-4eb1-86b1-d5acf18673ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Agent'])[6]/preceding::button[1]</value>
      <webElementGuid>a2ee71aa-48ca-4fe2-b361-7aaf2c8507c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/form/div/div/div/div/div/div/div/button[2]</value>
      <webElementGuid>ec9f9af9-c190-4e7b-aa17-864dde025950</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'advbtntab_report_agent_activity' and @type = 'button']</value>
      <webElementGuid>ebecee70-2dc8-4e77-8e3a-c848bf5ed885</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
