<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search</name>
   <tag></tag>
   <elementGuidId>053edd98-3a17-43e9-89e0-92715e1a53a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id='searchbtn'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#form_tab_report_agent_activity > div.animated.fadeInRight.p-t-xs > div.wrapper.wrapper-content.p-t-none > div.ibox-content > div.row.no-margins > div.col-sm-2.pull-right.p-r-none.m-b > div.row.no-margins > div.btn-group.pull-right > #searchbtn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>414346a2-d2e1-4694-b8b2-a06ee6df546d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>d8ade041-4870-4437-99ca-f02526f7af9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchbtn</value>
      <webElementGuid>6d19dea6-a6ba-41bb-ac1b-43b892965d28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-sm animated fadeInRight</value>
      <webElementGuid>e9fc7365-f924-4e41-a9e9-4441904eceaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e4f10a91-f4bf-4e6a-93ba-41ad2296d89a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
									 Search
								</value>
      <webElementGuid>8a8c934f-dcda-47a6-8ff5-1c782155bbeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_tab_report_agent_activity&quot;)/div[@class=&quot;animated fadeInRight p-t-xs&quot;]/div[@class=&quot;wrapper wrapper-content p-t-none&quot;]/div[@class=&quot;ibox-content&quot;]/div[@class=&quot;row no-margins&quot;]/div[@class=&quot;col-sm-2 pull-right p-r-none m-b&quot;]/div[@class=&quot;row no-margins&quot;]/div[@class=&quot;btn-group pull-right&quot;]/button[@id=&quot;searchbtn&quot;]</value>
      <webElementGuid>312db21a-130e-497b-95d2-a881d5f90518</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@id='searchbtn'])[2]</value>
      <webElementGuid>2ebc9166-0ae3-4d33-9629-c2d5ec9dc786</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_tab_report_agent_activity']/div/div/div/div/div/div/div/button</value>
      <webElementGuid>4808bbab-af91-458b-a535-4fddc9158ba4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Report Agent Activity'])[1]/following::button[1]</value>
      <webElementGuid>329fddd4-ef00-405d-aa42-e61c9dd7d748</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[20]/following::button[1]</value>
      <webElementGuid>4bd26a9d-262e-4f4b-b85f-c1910af6e6fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Team'])[20]/preceding::button[2]</value>
      <webElementGuid>458eb612-03df-409a-a667-3bfe5e29a63b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Agent'])[6]/preceding::button[2]</value>
      <webElementGuid>4d31447c-0a7b-4672-8120-ced1696ca5ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/form/div/div/div/div/div/div/div/button</value>
      <webElementGuid>af9a98c7-502f-4669-b1e9-fd7da5bcb54e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'search' and @id = 'searchbtn' and @type = 'button' and (text() = '
									 Search
								' or . = '
									 Search
								')]</value>
      <webElementGuid>f900e36f-7d6a-45c1-84e3-8eacfc1e173c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
