<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Today</name>
   <tag></tag>
   <elementGuidId>6c371d62-0db7-4b32-91d7-45e4e790b102</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-searchperiodetab_report_agent_activity-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-searchperiodetab_report_agent_activity-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a3b9b1d1-f287-4e20-8abd-1ff64ee941cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>264afcdf-277f-49fb-95a7-42ac28090fae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-searchperiodetab_report_agent_activity-container</value>
      <webElementGuid>6d975379-b8a7-4cb5-8a83-9b8c79bbb028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Today</value>
      <webElementGuid>2c533b56-f452-4d64-a1b5-15c0ab532b69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Today</value>
      <webElementGuid>66c725df-130c-4daf-9ad5-be673a63eef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-searchperiodetab_report_agent_activity-container&quot;)</value>
      <webElementGuid>e3e41969-01e7-4f87-aed6-7b9b70e5d277</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-searchperiodetab_report_agent_activity-container']</value>
      <webElementGuid>7d1c1ba8-49bb-4dec-b839-766efe4773e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='advfiltertab_report_agent_activity']/div/div[3]/span/span/span/span</value>
      <webElementGuid>422ac80f-b68f-49e2-a212-b14387a5f134</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Agent'])[6]/following::span[6]</value>
      <webElementGuid>25af32ac-6614-4087-b406-ff263348030e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Team'])[20]/following::span[12]</value>
      <webElementGuid>143db8f3-d5a9-4708-913f-7f8a6aca0ce3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Processing...'])[5]/preceding::span[5]</value>
      <webElementGuid>e0c672cd-872f-4b3f-a673-4364f012cb78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copy'])[5]/preceding::span[5]</value>
      <webElementGuid>d4bc5ace-07f1-451f-b8c8-5a89c85f9f50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/form/div/div/div/div/div[2]/div/div[3]/span/span/span/span</value>
      <webElementGuid>78bd246e-bfb7-4a0c-914e-f95b3f48785c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-searchperiodetab_report_agent_activity-container' and @title = 'Today' and (text() = 'Today' or . = 'Today')]</value>
      <webElementGuid>7f9684e3-7a46-4a3e-af11-dae6be3ef3c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
